// main.js minimal but with core features
const { auth, db, storage } = window.FB;
(function buildUI(){ const modal = document.createElement('div'); modal.innerHTML = `<div id="modalOverlay" class="modal-overlay hidden" role="dialog" aria-modal="true"><div class="modal"><button class="closeBtn" id="closeModal">&times;</button><h3>Login Rahasia</h3><div class="tabs"><button class="tab active" data-tab="admin">Admin</button><button class="tab" data-tab="guru">Guru</button></div><div class="tabcontent" id="adminTab"><label>Email admin: <input id="adminUser" type="email"></label><label>Password: <input id="adminPass" type="password"></label><div class="row"><button id="adminLoginBtn">Masuk sebagai Admin</button><button id="adminForgotBtn" class="link">Lupa Password</button></div></div><div class="tabcontent hidden" id="guruTab"><label>Email guru: <input id="guruUser" type="email"></label><label>Password: <input id="guruPass" type="password"></label><div class="row"><button id="guruLoginBtn">Masuk sebagai Guru</button><button id="guruForgotBtn" class="link">Lupa Password</button></div></div></div></div>`; document.body.appendChild(modal); const dash = document.createElement('div'); dash.id='dashboard'; dash.className='hidden'; dash.innerHTML=`<nav class="dash-sidebar"><div class="dash-top"><img id="dashLogo" src="assets/logo.png" alt="Logo"/><h3 id="dashSchoolName">SDN NAGREG</h3><p id="dashUserInfo"></p></div><ul id="dashMenu"></ul><div class="dash-footer"><button id="logoutBtn">Logout</button></div></nav><section class="dash-main"><header class="dash-header"><h2 id="dashTitle">Dashboard</h2></header><div id="dashContent" class="dash-content"></div></section>`; document.body.appendChild(dash); })();
// wiring
const schoolNameEl=document.getElementById('schoolName'), modalOverlay=document.getElementById('modalOverlay'), adminLoginBtn=document.getElementById('adminLoginBtn'), guruLoginBtn=document.getElementById('guruLoginBtn'), adminUserInput=document.getElementById('adminUser'), adminPassInput=document.getElementById('adminPass'), guruUserInput=document.getElementById('guruUser'), guruPassInput=document.getElementById('guruPass'), adminForgotBtn=document.getElementById('adminForgotBtn'), guruForgotBtn=document.getElementById('guruForgotBtn'), closeModalBtn=document.getElementById('closeModal'), studentEnterBtn=document.getElementById('studentEnter'), dashboard=document.getElementById('dashboard'), logoutBtn=document.getElementById('logoutBtn');
let tapCount=0, tapTimer=null, currentUser=null, currentProfile=null;
schoolNameEl.addEventListener('click', ()=>{ tapCount++; if(tapTimer) clearTimeout(tapTimer); tapTimer=setTimeout(()=>tapCount=0,1200); if(tapCount>=5){ tapCount=0; openModal(); }});
function openModal(){ modalOverlay.classList.remove('hidden'); adminPassInput.value=''; guruPassInput.value=''; }
closeModalBtn.addEventListener('click', ()=> modalOverlay.classList.add('hidden'));
if(location.search.indexOf('admin=true')!==-1) openModal();
// auth handlers
adminLoginBtn.addEventListener('click', async ()=>{ const email=adminUserInput.value.trim(), pass=adminPassInput.value; try{ const cred=await auth.signInWithEmailAndPassword(email,pass); currentUser=cred.user; await loadProfileAndOpen(); modalOverlay.classList.add('hidden'); }catch(e){ alert('Login gagal: '+e.message); }});
guruLoginBtn.addEventListener('click', async ()=>{ const email=guruUserInput.value.trim(), pass=guruPassInput.value; try{ const cred=await auth.signInWithEmailAndPassword(email,pass); currentUser=cred.user; await loadProfileAndOpen(); modalOverlay.classList.add('hidden'); }catch(e){ alert('Login gagal: '+e.message); }});
// student quick view
studentEnterBtn.addEventListener('click', async ()=>{ const nis=prompt('Masukkan NIS (contoh:1001):'); if(!nis) return; const sdoc=await db.collection('data_siswa').doc(nis).get(); if(!sdoc.exists) return alert('Siswa tidak ditemukan.'); const s=sdoc.data(); const contact=s.guardianPhone||''; if(contact){ if(confirm(`${s.name}\nKelas:${s.kelas}\nWA:${contact}\n\nBuka chat WA?`)) window.open('https://wa.me/'+contact.replace(/[^0-9]/g,'')+'?text='+encodeURIComponent('Halo, saya ingin konfirmasi akun Tabungan Siswa (NIS:'+nis+')')); }else alert('Kontak wali/guru belum diset.'); });
// minimal profile loader & dashboard show
async function loadProfileAndOpen(){ if(!currentUser) return; const uid=currentUser.uid; const up=await db.collection('users').doc(uid).get(); if(!up.exists){ await db.collection('users').doc(uid).set({ role:'guru', name:currentUser.displayName||currentUser.email, email:currentUser.email }); currentProfile={role:'guru', name:currentUser.displayName||currentUser.email}; } else currentProfile=up.data(); openDashboard(); }
auth.onAuthStateChanged(async (u)=>{ currentUser=u; if(u){ const up=await db.collection('users').doc(u.uid).get(); if(up.exists) currentProfile=up.data(); else currentProfile=null; } else currentProfile=null; });
function openDashboard(){ document.getElementById('app').classList.add('hidden'); dashboard.classList.remove('hidden'); buildMenuByRole(); renderDashHome(); }
logoutBtn.addEventListener('click', async ()=>{ await auth.signOut(); dashboard.classList.add('hidden'); document.getElementById('app').classList.remove('hidden'); });
function buildMenuByRole(){ const dashMenu=document.getElementById('dashMenu'); dashMenu.innerHTML=''; const role=(currentProfile&&currentProfile.role)||'guest'; const items=[]; if(role==='admin'){ items.push({id:'home',label:'Beranda'},{id:'manage_guru',label:'Manajemen Guru'},{id:'manage_kelas',label:'Manajemen Kelas'},{id:'manage_siswa',label:'Manajemen Siswa'},{id:'transaksi',label:'Transaksi & Rekap'},{id:'settings',label:'Pengaturan & Ubah Password'}); } else if(role==='guru'){ items.push({id:'home',label:'Beranda'},{id:'my_students',label:'Siswa Saya'},{id:'transaksi',label:'Catat Transaksi'},{id:'settings',label:'Pengaturan (Lupa Password WA)'}); } else { items.push({id:'student_view',label:'Lihat Saldo & Riwayat'},{id:'student_profile',label:'Profil & Kontak Guru'}); } items.forEach(it=>{ const li=document.createElement('li'); const btn=document.createElement('button'); btn.textContent=it.label; btn.addEventListener('click', ()=> handleMenuClick(it.id)); li.appendChild(btn); dashMenu.appendChild(li); }); document.getElementById('dashUserInfo').textContent = currentProfile?`${currentProfile.name} (${currentProfile.role})`:currentUser?currentUser.email:'Tamu'; }
function handleMenuClick(id){ if(id==='home') renderDashHome(); else if(id==='manage_guru') renderManageGuru(); else if(id==='manage_kelas') renderManageKelas(); else if(id==='manage_siswa') renderManageSiswa(); else if(id==='transaksi') renderTransaksi(); else if(id==='settings') renderSettings(); else if(id==='my_students') renderMyStudents(); else if(id==='student_view') renderStudentView(); else if(id==='student_profile') renderStudentProfile(); }
function renderDashHome(){ document.getElementById('dashTitle').textContent='Dashboard'; document.getElementById('dashContent').innerHTML=`<div class="card"><h3>Selamat datang, ${currentProfile?currentProfile.name:'Pengguna'}</h3><p>Nama Sekolah: <strong>SDN NAGREG</strong></p></div>`; }
async function renderManageSiswa(){ document.getElementById('dashTitle').textContent='Manajemen Siswa'; document.getElementById('dashContent').innerHTML=`<div class="card"><button id="addSiswa">Tambah Siswa</button><div id="sList" style="margin-top:1rem"></div></div>`; document.getElementById('addSiswa').addEventListener('click', async ()=>{ const nis=prompt('NIS (unik):'); if(!nis) return; const name=prompt('Nama siswa:'); const kelas=prompt('Kelas:'); const phone=prompt('Nomor WA wali (opsional):'); const pass=prompt('Password awal siswa:','siswa123'); const email=nis+'@tabungasiswa.local'; try{ const userCred = await auth.createUserWithEmailAndPassword(email, pass); const uid = userCred.user.uid; await db.collection('data_siswa').doc(nis).set({ name: name||nis, kelas: kelas||'', guardianPhone: phone||'', uid }); alert('Siswa ditambahkan dan akun auth dibuat.'); renderManageSiswa(); }catch(e){ alert('Gagal membuat akun siswa: '+e.message); } }); const q=await db.collection('data_siswa').get(); const sList=document.getElementById('sList'); sList.innerHTML=''; q.forEach(doc=>{ const s=doc.data(); const nis=doc.id; const div=document.createElement('div'); div.innerHTML=`<strong>${s.name}</strong> (NIS:${nis}) - Kelas:${s.kelas||'-'} - WA:${s.guardianPhone||'-'} <button data-n="${nis}" class="edits">Edit</button> <button data-n="${nis}" class="dels">Hapus</button>`; sList.appendChild(div); }); sList.querySelectorAll('.edits').forEach(b=>b.addEventListener('click', async ()=>{ const n=b.dataset.n; const docSnap=await db.collection('data_siswa').doc(n).get(); if(!docSnap.exists) return; const s=docSnap.data(); const name=prompt('Nama:', s.name); const kelas=prompt('Kelas:', s.kelas); const phone=prompt('WA wali:', s.guardianPhone); const upd={}; if(name) upd.name=name; if(kelas) upd.kelas=kelas; if(phone) upd.guardianPhone=phone; await db.collection('data_siswa').doc(n).update(upd); renderManageSiswa(); })); sList.querySelectorAll('.dels').forEach(b=>b.addEventListener('click', async ()=>{ const n=b.dataset.n; if(confirm('Hapus siswa NIS '+n+'?')){ await db.collection('data_siswa').doc(n).delete(); renderManageSiswa(); } })); }
window._ts={renderManageSiswa};